## cartridge.properties for cartridge commerce_assets
demandware.cartridges.app_pwa_base.multipleLanguageStorefront=true
demandware.cartridges.app_pwa_base.id=app_pwa_base
demandware.cartridges.app_pwa_base.version=0.0.1